#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
nohup node $OPENSHIFT_REPO_DIR/diy/server.js $OPENSHIFT_DIY_IP \
$OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &
